import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { BsFillMoonStarsFill, BsImageAlt, BsFillMouse3Fill} from 'react-icons/bs'
import Canvas from '../components/Canvas'


export default function Home() {
  return (
    <div  className=' bg-black min-h-screen pt-5'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className=' container mx-auto'>
        <nav className='flex align-middle justify-between items-center'>
          <h1>Y.P.</h1>
          <ul className=' gap-4 flex items-center navigation'>
            <li className='flex items-center gap-2'><BsFillMoonStarsFill /></li>
            <li className='flex items-center gap-2'><BsImageAlt/> Bg animation</li>
            <li className='flex items-center gap-2'> <BsFillMouse3Fill/> Hover mode</li>
            <li><a href="">C.V.</a></li>
          </ul>
        </nav>
      </main>
      <Canvas />
    </div>
  )
}
